server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/house_service_db
    username: postgres
    password: Postgres@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: home_service_secret_key
